config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "courses#index"

  resources :courses

  get 'accounts/new', to: "accounts#new"
  post 'accounts', to: "accounts#create"

  get 'account/login', to: "sessions#new"
  post "account/sessions", to: "sessions#create"
  delete "account/logout", to: "sessions#destroy"

  post "courses/:id/enroll", to: "courses#enroll"

  namespace :admin do
    root to: "courses#index"
  end

end

app/models/account.rb
require 'bcrypt'

class Account < ApplicationRecord
  attr_accessor :password

  before_save :encrypt_password

  has_many :course_students, foreign_key: :student_id
  has_many :courses, through: :course_students

  enum role: [:student, :admin]

  # account = Account.new()
  # account.encrypt_password
  def encrypt_password
    if self.password.present?
      self.encrypted_password = BCrypt::Password.create(self.password)
    end
  end

  #  Account.authenticate_account
  def self.authenticate(email, password)
  #   if we have account which have email & password
  #     matches with input email & password in database
  #   return account
  #   else
  #   return false

    account = Account.where(email: email).first

    return false unless account && account.encrypted_password

    if BCrypt::Password.new(account.encrypted_password) == password
        return account
    else
      return false
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :description, length: {minimum: 20, maximum: 200}, allow_blank: true

  has_many :course_students
  has_many :students, class_name: "Account", through: :course_students
end

app/models/course_student.rb
class CourseStudent < ApplicationRecord
  belongs_to :course
  belongs_to :student, class_name: "Account", foreign_key: :student_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def account_params
    params.require(:account).permit(:name, :email, :password)
  end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < AdminController
  def index

  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def authenticate_admin!
    redirect_to root_path if @current_account.role != 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_account!

  def authenticate_account!
    if session[:current_account_id]
      @current_account = Account.where(id: session[:current_account_id]).first
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.all

    respond_to do |format|
      format.html
      format.json {render json: {courses: @courses}}
    end
	end

  def enroll
    @course_student = CourseStudent.create(student_id: @current_account.id,
      course_id: params[:id])

    respond_to do |format|
      format.js
      format.json { render json: { status: :ok } }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_account!, only: [:new, :create]

  def new
    if session[:current_account_id]
      return redirect_to root_path
    end
  end

  def create
    # binding.pry

    # if we can authenticate user
    # redirect root_path
    # else
    # render action new to re-enter login credentials

    authorized_account = Account.authenticate(params[:email], params[:password])

    if authorized_account
      session[:current_account_id] = authorized_account.id
      redirect_to root_path
    else
      render :new
    end

  end

  def destroy
    session[:current_account_id] = nil
    redirect_to account_login_path
  end

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/new.html.erb
<!--<form class="col-md-6 col-md-offset-3">-->
  <!--<div class="form-group">-->
    <!--<label for="email">Email address:</label>-->
    <!--<input type="email" class="form-control" id="email">-->
  <!--</div>-->
  <!--<div class="form-group">-->
    <!--<label for="pwd">Password:</label>-->
    <!--<input type="password" class="form-control" id="pwd">-->
  <!--</div>-->
  <!--<div class="checkbox">-->
    <!--<label><input type="checkbox"> Remember me</label>-->
  <!--</div>-->
  <!--<button type="submit" class="btn btn-default">Submit</button>-->
<!--</form>-->

<%= form_for @account, url: {action: "create"},
             html: {class: "col-md-6 col-md-offset-3"} do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

    <br />
    <%= f.submit "Create" %>
<% end %>

app/views/admin/courses/index.html.erb
Admin courses index page

app/views/courses/enroll.js.erb
alert('enroll successful - script type')

$("#course-<%= @course_student.course_id %>").fadeOut(200);

app/views/courses/index.html.erb
 <div id="course-index">
    <div class="container">
		<div class="row">

			<% @courses.each do |course| %>

				<div class="col-sm-4" id="course-<%= course.id %>">
					<div id="card" class="weater">
						<div class="city-selected">
							<article>
								<div class="info">
									<div class="city"><%= course.name %></div>
									<div class="night">Night - 22:07 PM</div>

									<div class="temp">3°</div>
								</div>

								<div class="icon">

								</div>

							</article>
            </div>

						<div class="days">
							<div class="row row-no-gutter">
								<div class="col-md-4 col-md-offset-8">
									<div class="day">
										<div class="btn btn-success btn-enrollment"
											data-id="<%= course.id %>"> Enroll </div>

									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

			<% end %>

		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>

    <div style="min-height: 800px">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>

</html>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer">
    <div class="container">
      <a href='#'><i class="fa fa-twitch fa-3x fa-fw"></i></a>
      <a href='#'><i class="fa fa-facebook fa-3x fa-fw"></i></a>
      <a href='#'><i class="fa fa-twitter fa-3x fa-fw"></i></a>
      <a href='#'><i class="fa fa-youtube-play fa-3x fa-fw"></i></a>
      <a href='#'><i class="fa fa-rss fa-3x fa-fw"></i></a>
      <a href='#'><i class="fa fa-vine fa-3x fa-fw"></i></a>
      <a href='#'><i class="fa fa-flickr fa-3x fa-fw"></i></a>
      <a href='#'><i class="fa fa-linkedin fa-3x fa-fw"></i></a>
      </span>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active">
        <%= link_to 'Home', root_path %>
      </li>

      <li>

        <% if session[:current_account_id] %>
            <%= link_to account_logout_path, method: :delete do %>
              Logout
            <% end %>
        <% else %>
            <%= link_to 'Login', account_login_path %>
        <% end %>

      </li>

    </ul>
  </div>
</nav>